version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building and deploying Lambda function"
      - npx serverless deploy --stage dev --region us-east-1
