version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing global dependencies..."
      - npm install -g serverless
      - echo "Logging in to Serverless Framework..."
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile serverless_profile
  build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
      - echo "Deploying Lambda function..."
      - serverless deploy
