version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm install 
      - npm install axios

  pre_build:
    commands:
      - echo "Verifying Node.js version"
      - node -v
      - echo "Verifying npm version"
      - npm -v

  build:
    commands:
      - echo "Running the build"
      - sam build

  post_build:
    commands:
      - echo "Build is complete."

artifacts:
  files:
    - '**/*'  