version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Verifying Node.js version"
      - node -v
      - echo "Verifying npm version"
      - npm -v
  build:
    commands:
      - echo "Building the Lambda function"
      - npm run build --if-present
  post_build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - '**/*'
