service: chloe-backend

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    GHL_API_KEY: ${env:GHL_API_KEY}
    GHL_WEBHOOK_SECRET: ${env:GHL_WEBHOOK_SECRET}
    GHL_LOCATION_ID: ${env:GHL_LOCATION_ID}

functions:
  yourFunction:
    handler: handler.main
