service: chloe-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  chloePreQualInbound:
    handler: functions/chloePreQualInbound.handler
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      GHL_API_KEY: ${env:GHL_API_KEY}
      GHL_WEBHOOK_SECRET: ${env:GHL_WEBHOOK_SECRET}
      GHL_LOCATION_ID: ${env:GHL_LOCATION_ID}

plugins:
  - serverless-offline  # Se você estiver testando localmente

resources:
  Resources:
    MyLambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: LambdaExecutionPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:ListBucket"
                    - "s3:GetObject"
                  Resource:
                    - "arn:aws:s3:::YOUR_BUCKET_NAME"
                    - "arn:aws:s3:::YOUR_BUCKET_NAME/*"
