AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Atualiza código da função Lambda existente sem trocar role ou nome

Resources:

  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Não definir FunctionName nem Role para não substituir a função existente
      Handler: src/functions-lambda/sendmessage.handler
      Runtime: nodejs22.x
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          NODE_ENV: "production"
      Events:
        SendMessageApi:
          Type: Api
          Properties:
            Path: /send-message
            Method: post
